[project]
name = "sendify-challange"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.26.0",
    "playwright>=1.58.0",
    "requests>=2.32.5",
]
